### ISSUE TITLE
Monaca LocalKit menu issues

### ISSUE THREAD

**Issue by svdoever** [monaca/Localkit#10]
* Preferences menu item does not do anything
* Monaca LocalKit Help menu item does not non-existing page

**Comment by svdoever** [comment]
Documentation show screenshot of Preferences (https://docs.monaca.io/en/manual/development/monaca_localkit/overview/#usage), but is not working on my Mac

**Comment by svdoever** [comment]
After restart of Monaca LocalKit the preferences link started to work.

**Comment by andipavllo** [comment]
Preferences should work correctly, at least I never encountered any issue with them.

Regarding the help menu, I fixed a dead link. Will be available from next release.
