### ISSUE TITLE
Release 2.1.3 - Remote Build and Build Settings fail with strange screen 

### ISSUE THREAD

**Issue by belalothman** [monaca/Localkit#18]
I get this screen when I am press on building settings, I am working on windows 10
![dp1bff9](https://cloud.githubusercontent.com/assets/16001137/21890694/2ebb8bf4-d8cf-11e6-9f30-67f9d30cd157.png)

**Comment by andipavllo** [comment]
@belalothman I will test it but there may be some issues with your local environment rather than with Localkit. Could you please tell me which template have you been using in that app?

**Comment by belalothman** [comment]
@andipavllo I installed the application in this tutorial https://onsen.io/blog/onsen-ui-youtube-api-v3/,
even if I make any new project with any templates I get the same error when tring to press Build Settings.
Is there any log files I can send it to you?
for me it is urgent because I almost finished my application and need to build it but unfortunatelyI can't.

**Comment by andipavllo** [comment]
@belalothman I just tried with the latest version and everything works fine on my environment. Are you using any proxy settings? 
I suggest you to go to your Cordova folder

`C:\Users\YOUR_USER\.cordova`

and run `npm install`.
