### ISSUE TITLE
iOS release build is missing Bundle ID

### ISSUE THREAD

**Issue by JamalAPI** [monaca/Localkit#29]
Using Monaca Localkit, when trying to upload an iOS iap, via Apple's Transporter app, it reportd a missing application id.

**The app's bundle id is nil**

Using Monaca IDE, the files uploads successfully.

Tested with Localkit 3.4.4 and 4.0 RC1.

**Comment by yong-asial** [comment]
@JamalAPI hi, if it is successful using Cloud IDE there must be some missing files or configuration in local file (localkit). Could you try the following steps:
- build in cloud IDE
- then in localkit, click download and overwrite all the files. Then build again using localkit.
(To see the differences maybe you could use git to see the status before and after the download)

**Comment by JamalAPI** [comment]
@yong-asial, I exported the project from the cloud ID to a zip file, then in LocalKit I imported the zip file into **a new folder** but I am stilling the error when using Transport.

Here the exact error message:
**Failed to create the .itmsp for myproject.ipa 
The app's bundle id is nil**

However, the app bundle ID is accurate and it's all lower case.

BTW, never had such a problem before.

**Comment by yong-asial** [comment]
@JamalAPI could you check the .monacaignore file. It working very similar to .gitignore but using for download/upload between Monaca cloud and local (localkit and cli). Maybe there is some files not uploading to the cloud due to this configuration.

**Comment by JamalAPI** [comment]
@yong-asial, here is the content of .monacaignore file:

````
/.monaca/*
!/.monaca/project_info.json
/platforms
.DS_Store
*.swp
.vscode/
typings/
node_modules
.git
````

**Comment by JamalAPI** [comment]
It seems the Monaca updates to iOS 6.1.1 solved the issue. Tested today and I was able to upload a new version of the app Test Flight.
