### ISSUE TITLE
2022/01/11_Monaca serve build error

### ISSUE THREAD

**Issue by TPGT00019** [monaca/Localkit#31]
Dear Monaca team,
Today (2022/01/11) I have build release project but can not success.
Building logs has error "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory" message.

This maybe not by Localkit tool but Monaca team can check this.

Links error: http://prntscr.com/26c9lai

Thanks & Brs,

**Comment by yong-asial** [comment]
Hi @TPGT00019 .
This might the problem of `cordova-custom-config` plugin if you have it in your project. 
You may try adding "colors": "1.4.0" to the plugin or project dependencies
Please refer to the following for more detail

- https://monaca.io/headline/fault.html
- https://github.com/dpa99c/cordova-custom-config/pull/172

**Comment by TPGT00019** [comment]
Hi @yong-asial 

Thanks for this answer.
I added "colors": "1.4.0" to the dependencies of package.json file and bug has fixed.

**Comment by yong-asial** [comment]
Thank you, I'll close the ticket.
